# Generated by Django 5.0.6 on 2024-08-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_jugador_jugador_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=5)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_curso', 'En curso'), ('terminada', 'Terminada')], default='iniciada', max_length=10)),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(default='098fc9410c074bf8b0aea4e77d1a7244', max_length=100)),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_iniciadas', to='usuarios.jugador')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_recibidas', to='usuarios.jugador')),
            ],
        ),
    ]
