# Generated by Django 5.0.6 on 2024-06-29 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('usuarios', '0005_alter_jugador_jugador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participantes',
            field=models.ManyToManyField(related_name='chats', to='usuarios.jugador'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.jugador'),
        ),
    ]
