# Generated by Django 5.0.6 on 2024-06-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('jugador_id', models.CharField(default='EC243E53', max_length=10, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('amigos', models.ManyToManyField(related_name='mis_amigos', through='usuarios.Amistad', to='usuarios.jugador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganados', models.IntegerField(default=0)),
                ('perdidos', models.IntegerField(default=0)),
                ('empatados', models.IntegerField(default=0)),
                ('jugados', models.IntegerField(default=0)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='amistad',
            name='from_jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_jugador', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='amistad',
            name='to_jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_jugador', to='usuarios.jugador'),
        ),
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_solicitudes', to='usuarios.jugador')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_solicitudes', to='usuarios.jugador')),
            ],
        ),
    ]
