# Generated by Django 5.0.6 on 2024-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='jugador_id',
            field=models.CharField(default='49BD8067', max_length=10, unique=True),
        ),
    ]
