# Generated by Django 5.0.6 on 2024-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_jugador_jugador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='jugador_id',
            field=models.CharField(default='1F4CBBD1', max_length=10, unique=True),
        ),
    ]
