# Generated by Django 5.0.6 on 2024-06-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_jugador_last_seen_alter_jugador_jugador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='jugador_id',
            field=models.CharField(default='91477C1B', max_length=10, unique=True),
        ),
    ]
