# Generated by Django 5.0.6 on 2024-08-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_jugador_jugador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='jugador_id',
            field=models.CharField(default='ACE8A55E', max_length=10, unique=True),
        ),
    ]
