# Generated by Django 5.0.6 on 2024-06-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado')], default='EN PROGRESO', max_length=15)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_ganados', to=settings.AUTH_USER_MODEL)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_como_jugador1', to=settings.AUTH_USER_MODEL)),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_como_jugador2', to=settings.AUTH_USER_MODEL)),
                ('turno_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_en_turno', to=settings.AUTH_USER_MODEL)),
                ('tablero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juego', to='juego.tablero')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_partidas', to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='juego.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tiempo_restante', models.IntegerField(default=30)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='juego.juego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
